import React from "react";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getAllNewsSources } from "../api";
import TileList from "../components/TileList";
import { Source } from "../types/source";
import Header from "../components/Header";

const Home: NextPage = ({ sources }: any) => {
  const englishSources = sources.sources.filter(
    (source: Source) => source.language === "en"
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TileList sources={englishSources} />
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const sources = await getAllNewsSources();

  return {
    props: {
      sources,
    },
  };
};

export default Home;
